### ISSUE TITLE
If Script's timezone is different than calendar, all day events are created on the wrong day

### ISSUE THREAD

**Issue by derekantrican** [derekantrican/GAS-ICS-Sync#34]
### Setup:

**Calendar timezone:** Central time - Chicago
**Script timezone:** Pacific Time
**Test string ([wiki](https://github.com/derekantrican/GAS-ICS-Sync/wiki/Debugging-tips)):**

    var sourceCalendarString =
    "BEGIN:VCALENDAR\n"+
    "PRODID;X-RICAL-TZSOURCE=TZINFO:-//com.denhaven2/NONSGML ri_cal gem//EN\n"+
    "CALSCALE:GREGORIAN\n"+
    "VERSION:2.0\n"+
    "METHOD:PUBLISH\n"+
    "BEGIN:VTIMEZONE\n"+
    "TZID;X-RICAL-TZSOURCE=TZINFO:America/Chicago\n"+
    "BEGIN:STANDARD\n"+
    "DTSTART:20181104T020000\n"+
    "RDATE:20181104T020000\n"+
    "TZOFFSETFROM:-0500\n"+
    "TZOFFSETTO:-0600\n"+
    "TZNAME:CST\n"+
    "END:STANDARD\n"+
    "BEGIN:DAYLIGHT\n"+
    "DTSTART:20190310T020000\n"+
    "RDATE:20190310T020000\n"+
    "TZOFFSETFROM:-0600\n"+
    "TZOFFSETTO:-0500\n"+
    "TZNAME:CDT\n"+
    "END:DAYLIGHT\n"+
    "END:VTIMEZONE\n"+
    "BEGIN:VEVENT\n"+
    "DTEND;VALUE=DATE:20190408\n"+
    "DTSTART;VALUE=DATE:20190407\n"+
    "DTSTAMP;VALUE=DATE-TIME:20190221T204949Z\n"+
    "UID:event_448196497_ngin.com\n"+
    "DESCRIPTION:Tag(s): 14U Mascheri\nhttps://sportsengine.page.link/?al=spor\n"+
    " tsengine%3A%2F%2Fevent%2F448196497%3Fevent_start_time%3D2019-04-07T05%25\n"+
    " 3A00%253A00Z%26team_ids%255B%255D%3D2830426&apn=com.sportngin.android&ct\n"+
    " =iCalEventLink&ibi=com.ngin.sport.iphone&isi=499597400&link=http%3A%2F%2\n"+
    " Fwww.lakecountystars.org%2Fevent%2Fshow%2F448196497%3Fresource_id%3D4481\n"+
    " 96497%26start_time%3D2019-04-07T05%253A00%253A00Z%26team_ids%255B%255D%3\n"+
    " D2830426%26type%3Devent&pt=319609&utm_campaign=iCalEventLink\n"+
    "SUMMARY:14U Mascheri - Picture Day (time is TBD)\n"+
    "LOCATION:\n"+
    "END:VEVENT\n"+
    "END:VCALENDAR";

![image](https://i.imgur.com/ItP4tEo.png)

Note how event in ics is set for April 7th, but is created on April 6th. If the Script timezone is changed to match the calendar (eg Central Time) then the issue disappears. We should make this rely on the calendar or ics timezone - not the Script timezone

**Comment by michaelcadilhac** [comment]
Additionally (though probably unrelated), it seems that if the script is to create the calendar, it's set to GMT, making the events appear shifted.  This may be fixed by using CalendarApp.setTimeZone on creation, not entirely sure.  Changing the timezone *after* the events are created seems to have no impact.

**Comment by jonas0b1011001** [comment]
Easiest fix should be editing the toJSDate function in ical.js to return a Date instead of DateTime for AllDay-Events.
```
toJSDate: function toJSDate() {
      if (this.zone == ICAL.Timezone.localTimezone) {
        if (this.isDate) {
          return new Date(this.year, this.month - 1, this.day);
        } else {
          return new Date(this.year, this.month - 1, this.day,
                          this.hour, this.minute, this.second, 0);
        }
      } else {
        if (this.isDate) {
          return new Date(this.year, this.month - 1, this.day);
        } else {
          return new Date(this.toUnixTime() * 1000);
        }
      }
    }
```

**Comment by amytencza** [comment]
seeing incorrect timezone on an hour long meeting as well. script runs in same timezone as my calendar. although owner of the original event may be in another timezone, so it's possibly not converting the ical timezone to my timezone properly....

DTSTART;TZID=Central Standard Time:20190711T130000
DTEND;TZID=Central Standard Time:20190711T140000

my script and calendar are in arizona/phoenix timezone, not central standard. it syncs as 1-2pm on my calendar, but it should be 11am-12pm

**Comment by bearded22** [comment]
I'm encountering a similar problem for events as @amytencza. Events that have been created in a different time zone end up at the wrong location in my calendar. Event is created in India and should apprear at 11:00 but it appears at 14:30.

When I check the logs I see the following:
**05:30:00 GMT-0700**  but India should be at **GMT-5.5**. It is showing op at the right time in the original calendar.

**Comment by derekantrican** [comment]
Fixed with #51 . Will release a new version soon

**Comment by michaelcadilhac** [comment]
I believe the _title_ of this bug report is still not fixed, at least.  If I don't set the script's timezone to the ICS's, then events are placed at the wrong time.

**Comment by derekantrican** [comment]
Ok, I'll reopen this so we make sure to check it

**Comment by jonas0b1011001** [comment]
> I believe the _title_ of this bug report is still not fixed, at least. If I don't set the script's timezone to the ICS's, then events are placed at the wrong time.

Do you have a setup where the event in post 1 is created on the wrong day? Can't reproduce the issue with the latest commit.

**Comment by derekantrican** [comment]
The initial comment on this issue should have a setup that shows the issue

**Comment by michaelcadilhac** [comment]
Sure thing.  I had the script on BST and this ical:
```
BEGIN:VCALENDAR
VERSION:2.0
X-WR-CALNAME:OrgMode Calendar
X-WR-TIMEZONE:America/Chicago
BEGIN:VTIMEZONE
TZID:America/Chicago
END:VTIMEZONE
BEGIN:VEVENT
UID:TS1-9ef8856e-5c34-4d40-a13b-4f702d0c5c76
DTSTART:20190910T110000
DTEND:20190910T130000
SUMMARY:My Test at 11am
END:VEVENT
END:VCALENDAR
```
The log then says that the event is at 11 BST, instead of central time.  This is still true if:
- The target calendar is in UTC/BST/CST
- The TZID is "America/Chicago" or "CST"
- The VTIMEZONE section is fully fledged.

**Comment by jonas0b1011001** [comment]
I don't think that the ics you provided is valid.

1.  VTimezone is missing UTC-Offsets
2. DTSTART and DTEND have no tzid property assigned, therefore they are interpreted as floating

After fixing these, it actually worked fine:

```
var newSrc = "BEGIN:VCALENDAR\n" +
"VERSION:2.0\n" +
"X-WR-CALNAME:OrgMode Calendar\n" +
"X-WR-TIMEZONE:America/Chicago\n" +
"BEGIN:VTIMEZONE\n"+
"TZID;X-RICAL-TZSOURCE=TZINFO:America/Chicago\n"+
"BEGIN:STANDARD\n"+
"DTSTART:20181104T020000\n"+
"RDATE:20181104T020000\n"+
"TZOFFSETFROM:-0500\n"+
"TZOFFSETTO:-0600\n"+
"TZNAME:CST\n"+
"END:STANDARD\n"+
"BEGIN:DAYLIGHT\n"+
"DTSTART:20190310T020000\n"+
"RDATE:20190310T020000\n"+
"TZOFFSETFROM:-0600\n"+
"TZOFFSETTO:-0500\n"+
"TZNAME:CDT\n"+
"END:DAYLIGHT\n"+
"END:VTIMEZONE\n"+
"BEGIN:VEVENT\n" +
"UID:TS1-9ef8856e-5c34-4d40-a13b-4f702d0c5c76\n" +
"DTSTART;TZID=America/Chicago:20190910T110000\n" +
"DTEND;TZID=America/Chicago:20190910T130000\n" +
"SUMMARY:My Test at 11am\n" +
"END:VEVENT\n" +
"END:VCALENDAR\n";
```

<img width="441" alt="Bildschirmfoto 2019-08-31 um 18 26 20" src="https://user-images.githubusercontent.com/43352574/64066652-ec78c880-cc1c-11e9-96f9-792fb61cb9b5.png">

**Comment by derekantrican** [comment]
@jonas0b1011001 I think some services (maybe Outlook & Google Calendar) might have those values hardcoded for IANA timezones like `America/Chicago`

**Comment by jonas0b1011001** [comment]
That might be the case, nevertheless it's not valid and i'm not sure how we would be able to compensate the missing information.
> One of 'standardc' or 'daylightc' MUST occur and each MAY occur more than once.

**Comment by michaelcadilhac** [comment]
I did mention that a fully fledged VTIMEZONE does not solve the problem, but I wasn't aware of the notion of floating  time.  As per the [iCalendar specification](https://www.kanzaki.com/docs/ical/dateTime.html):

> The use of local time in a DATE-TIME value without the TZID property parameter is to be interpreted as floating time, regardless of the existence of "VTIMEZONE" calendar components in the iCalendar object.

I was wrongly expecting that the VTIMEZONE would apply. 

 It can however be argued that the right behavior is to use the target calendar timezone rather than the script's; I would expect users to understand the concept of calendar timezone better than _script_ timezone.  Depending on how you feel about that, please close this issue or leave it open.

For information, this ics was produced by org-mode, which certainly approximates the standard.

Sorry for the noise and thanks for the support.

**Comment by jonas0b1011001** [comment]
> It can however be argued that the right behavior is to use the target calendar timezone rather than the script's; I would expect users to understand the concept of calendar timezone better than _script_ timezone. Depending on how you feel about that, please close this issue or leave it open.

Totally agree, will try to adjust it :)

**Comment by rubendibattista** [comment]
Same here:
```
var sourceCalendarString =
    "BEGIN:VCALENDAR\r\nX-WR-CALNAME:Calendar\r\nX-WR-CALID:3a756a8b-bf83-48f3-92f9-da383e04e056:10\r\nPRODID:Zimbra-Calendar-Provider\r\nVERSION:2.0\r\nMETHOD:PUBLISH\r\nBEGIN:VTIMEZONE\r\nTZID:America\/Los_Angeles\r\nBEGIN:STANDARD\r\nDTSTART:16010101T020000\r\nTZOFFSETTO:-0800\r\nTZOFFSETFROM:-0700\r\nRRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=11;BYDAY=1SU\r\nTZNAME:PST\r\nEND:STANDARD\r\nBEGIN:DAYLIGHT\r\nDTSTART:16010101T020000\r\nTZOFFSETTO:-0700\r\nTZOFFSETFROM:-0800\r\nRRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=3;BYDAY=2SU\r\nTZNAME:PDT\r\nEND:DAYLIGHT\r\nEND:VTIMEZONE\r\nBEGIN:VTIMEZONE\r\nTZID:Europe\/Paris\r\nBEGIN:STANDARD\r\nDTSTART:16010101T030000\r\nTZOFFSETTO:+0100\r\nTZOFFSETFROM:+0200\r\nRRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=10;BYDAY=-1SU\r\nTZNAME:CET\r\nEND:STANDARD\r\nBEGIN:DAYLIGHT\r\nDTSTART:16010101T020000\r\nTZOFFSETTO:+0200\r\nTZOFFSETFROM:+0100\r\nRRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=3;BYDAY=-1SU\r\nTZNAME:CEST\r\nEND:DAYLIGHT\r\nEND:VTIMEZONE\r\nBEGIN:VTIMEZONE\r\nTZID:Europe\/Brussels\r\nBEGIN:STANDARD\r\nDTSTART:16010101T030000\r\nTZOFFSETTO:+0100\r\nTZOFFSETFROM:+0200\r\nRRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=10;BYDAY=-1SU\r\nTZNAME:CET\r\nEND:STANDARD\r\nBEGIN:DAYLIGHT\r\nDTSTART:16010101T020000\r\nTZOFFSETTO:+0200\r\nTZOFFSETFROM:+0100\r\nRRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=3;BYDAY=-1SU\r\nTZNAME:CEST\r\nEND:DAYLIGHT\r\nEND:VTIMEZONE\r\nBEGIN:VEVENT\r\nUID:040000008200E00074C5B7101A82E00800000000E012E4FCBA6CD5010000000000000000\r\n 10000000A75FBA59B47C784ABD42E4B8ABC7A329\r\nSUMMARY:Point C\'Space\r\nDESCRIPTION:Voil\u00E0 une invitation pour la r\u00E9union de mercredi.\\n\\nJe propose \r\n que l\u2019on se retrouve devant le bureau de Ruben (Bureau 2003 de l\u2019aile CMAP).\r\n \\n\\nA plus tard\\,\\n\\nNicolas\\n\\n\r\nX-ALT-DESC;FMTTYPE=text\/html:<html xmlns:v=\"urn:schemas-microsoft-com:vml\" x\r\n mlns:o=\"urn:schemas-microsoft-com:office:office\" xmlns:w=\"urn:schemas-micros\r\n oft-com:office:word\" xmlns:m=\"http:\/\/schemas.microsoft.com\/office\/2004\/12\/om\r\n ml\" xmlns=\"http:\/\/www.w3.org\/TR\/REC-html40\"><head><meta http-equiv=Content-T\r\n ype content=\"text\/html\\; charset=iso-8859-1\"><meta name=Generator content=\"M\r\n icrosoft Word 15 (filtered medium)\"><style><!--\\n\/* Font Definitions *\/\\n@fo\r\n nt-face\\n{font-family:\"Cambria Math\"\\;\\npanose-1:2 4 5 3 5 4 6 3 2 4\\;}\\n@fo\r\n nt-face\\n{font-family:Calibri\\;\\npanose-1:2 15 5 2 2 2 4 3 2 4\\;}\\n@font-fac\r\n e\\n{font-family:Georgia\\;\\npanose-1:2 4 5 2 5 4 5 2 3 3\\;}\\n\/* Style Definit\r\n ions *\/\\np.MsoNormal\\, li.MsoNormal\\, div.MsoNormal\\n{margin:0cm\\;\\nmargin-b\r\n ottom:.0001pt\\;\\nfont-size:11.0pt\\;\\nfont-family:\"Calibri\"\\,sans-serif\\;}\\na\r\n :link\\, span.MsoHyperlink\\n{mso-style-priority:99\\;\\ncolor:#0563C1\\;\\ntext-d\r\n ecoration:underline\\;}\\na:visited\\, span.MsoHyperlinkFollowed\\n{mso-style-pr\r\n iority:99\\;\\ncolor:#954F72\\;\\ntext-decoration:underline\\;}\\np.msonormal0\\, l\r\n i.msonormal0\\, div.msonormal0\\n{mso-style-name:msonormal\\;\\nmso-margin-top-a\r\n lt:auto\\;\\nmargin-right:0cm\\;\\nmso-margin-bottom-alt:auto\\;\\nmargin-left:0cm\r\n \\;\\nfont-size:12.0pt\\;\\nfont-family:\"Times New Roman\"\\,serif\\;}\\nspan.EmailS\r\n tyle18\\n{mso-style-type:personal-compose\\;\\nfont-family:\"Georgia\"\\,serif\\;\\n\r\n color:windowtext\\;\\nfont-weight:normal\\;\\nfont-style:normal\\;}\\n.MsoChpDefau\r\n lt\\n{mso-style-type:export-only\\;\\nfont-size:10.0pt\\;\\nfont-family:\"Calibri\"\r\n \\,sans-serif\\;}\\n@page WordSection1\\n{size:612.0pt 792.0pt\\;\\nmargin:70.85pt\r\n  70.85pt 70.85pt 70.85pt\\;}\\ndiv.WordSection1\\n{page:WordSection1\\;}\\n--><\/s\r\n tyle><!--[if gte mso 9]><xml>\\n<o:shapedefaults v:ext=\"edit\" spidmax=\"1026\" \r\n \/>\\n<\/xml><![endif]--><!--[if gte mso 9]><xml>\\n<o:shapelayout v:ext=\"edit\">\r\n \\n<o:idmap v:ext=\"edit\" data=\"1\" \/>\\n<\/o:shapelayout><\/xml><![endif]--><\/hea\r\n d><body lang=EN-US link=\"#0563C1\" vlink=\"#954F72\"><div class=WordSection1><p\r\n  class=MsoNormal><span lang=FR style=\'font-size:10.0pt\\;font-family:\"Georgia\r\n \"\\,serif\'>Voil\u00E0 une invitation pour la r\u00E9union de mercredi.<o:p><\/o:p><\/span\r\n ><\/p><p class=MsoNormal><span lang=FR style=\'font-size:10.0pt\\;font-family:\"\r\n Georgia\"\\,serif\'>Je propose que l&#8217\\;on se retrouve devant le bureau de \r\n Ruben (Bureau 2003 de l&#8217\\;aile CMAP).<o:p><\/o:p><\/span><\/p><p class=Mso\r\n Normal><span lang=FR style=\'font-size:10.0pt\\;font-family:\"Georgia\"\\,serif\'>\r\n A plus tard\\,<o:p><\/o:p><\/span><\/p><p class=MsoNormal><span lang=FR style=\'f\r\n ont-size:10.0pt\\;font-family:\"Georgia\"\\,serif\'>Nicolas<o:p><\/o:p><\/span><\/p>\r\n <\/div><\/body><\/html>\r\nLOCATION:Bureau de Ruben 2003 CMAP\r\nATTENDEE;CN=Ruben Di Battista;PARTSTAT=ACCEPTED:mailto:ruben.di-battista@pol\r\n ytechnique.edu\r\nATTENDEE;CN=\"Assump\u00E7\u00E3o Scripnic Dimitri (M.)\":mailto:dimitri.assumpcao-scrip\r\n nic@polytechnique.edu\r\nPRIORITY:5\r\nORGANIZER;CN=Nicolas Hanappier:mailto:nicolas.hanappier@polytechnique.edu\r\nDTSTART;TZID=\"Europe\/Brussels\":20190918T140000\r\nDTEND;TZID=\"Europe\/Brussels\":20190918T150000\r\nSTATUS:CONFIRMED\r\nCLASS:PUBLIC\r\nX-MICROSOFT-CDO-INTENDEDSTATUS:BUSY\r\nTRANSP:OPAQUE\r\nLAST-MODIFIED:20190916T161723Z\r\nDTSTAMP:20190916T161723Z\r\nSEQUENCE:0\r\nBEGIN:VALARM\r\nACTION:DISPLAY\r\nTRIGGER;RELATED=START:-PT5M\r\nDESCRIPTION:Reminder\r\nEND:VALARM\r\nEND:VEVENT\r\nEND:VCALENDAR";
```
Original string (I'm not so great string management with JS so I just escaped everything in a single string): 
```
BEGIN:VCALENDAR
X-WR-CALNAME:Calendar
X-WR-CALID:3a756a8b-bf83-48f3-92f9-da383e04e056:10
PRODID:Zimbra-Calendar-Provider
VERSION:2.0
METHOD:PUBLISH
BEGIN:VTIMEZONE
TZID:America/Los_Angeles
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETTO:-0800
TZOFFSETFROM:-0700
RRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=11;BYDAY=1SU
TZNAME:PST
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETTO:-0700
TZOFFSETFROM:-0800
RRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=3;BYDAY=2SU
TZNAME:PDT
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:Europe/Paris
BEGIN:STANDARD
DTSTART:16010101T030000
TZOFFSETTO:+0100
TZOFFSETFROM:+0200
RRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=10;BYDAY=-1SU
TZNAME:CET
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETTO:+0200
TZOFFSETFROM:+0100
RRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=3;BYDAY=-1SU
TZNAME:CEST
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:Europe/Brussels
BEGIN:STANDARD
DTSTART:16010101T030000
TZOFFSETTO:+0100
TZOFFSETFROM:+0200
RRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=10;BYDAY=-1SU
TZNAME:CET
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETTO:+0200
TZOFFSETFROM:+0100
RRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=3;BYDAY=-1SU
TZNAME:CEST
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
UID:040000008200E00074C5B7101A82E00800000000E012E4FCBA6CD5010000000000000000
 10000000A75FBA59B47C784ABD42E4B8ABC7A329
SUMMARY:Point C'Space
DESCRIPTION:Voilà une invitation pour la réunion de mercredi.\n\nJe propose 
 que l’on se retrouve devant le bureau de Ruben (Bureau 2003 de l’aile CMAP).
 \n\nA plus tard\,\n\nNicolas\n\n
X-ALT-DESC;FMTTYPE=text/html:<html xmlns:v="urn:schemas-microsoft-com:vml" x
 mlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-micros
 oft-com:office:word" xmlns:m="http://schemas.microsoft.com/office/2004/12/om
 ml" xmlns="http://www.w3.org/TR/REC-html40"><head><meta http-equiv=Content-T
 ype content="text/html\; charset=iso-8859-1"><meta name=Generator content="M
 icrosoft Word 15 (filtered medium)"><style><!--\n/* Font Definitions */\n@fo
 nt-face\n{font-family:"Cambria Math"\;\npanose-1:2 4 5 3 5 4 6 3 2 4\;}\n@fo
 nt-face\n{font-family:Calibri\;\npanose-1:2 15 5 2 2 2 4 3 2 4\;}\n@font-fac
 e\n{font-family:Georgia\;\npanose-1:2 4 5 2 5 4 5 2 3 3\;}\n/* Style Definit
 ions */\np.MsoNormal\, li.MsoNormal\, div.MsoNormal\n{margin:0cm\;\nmargin-b
 ottom:.0001pt\;\nfont-size:11.0pt\;\nfont-family:"Calibri"\,sans-serif\;}\na
 :link\, span.MsoHyperlink\n{mso-style-priority:99\;\ncolor:#0563C1\;\ntext-d
 ecoration:underline\;}\na:visited\, span.MsoHyperlinkFollowed\n{mso-style-pr
 iority:99\;\ncolor:#954F72\;\ntext-decoration:underline\;}\np.msonormal0\, l
 i.msonormal0\, div.msonormal0\n{mso-style-name:msonormal\;\nmso-margin-top-a
 lt:auto\;\nmargin-right:0cm\;\nmso-margin-bottom-alt:auto\;\nmargin-left:0cm
 \;\nfont-size:12.0pt\;\nfont-family:"Times New Roman"\,serif\;}\nspan.EmailS
 tyle18\n{mso-style-type:personal-compose\;\nfont-family:"Georgia"\,serif\;\n
 color:windowtext\;\nfont-weight:normal\;\nfont-style:normal\;}\n.MsoChpDefau
 lt\n{mso-style-type:export-only\;\nfont-size:10.0pt\;\nfont-family:"Calibri"
 \,sans-serif\;}\n@page WordSection1\n{size:612.0pt 792.0pt\;\nmargin:70.85pt
  70.85pt 70.85pt 70.85pt\;}\ndiv.WordSection1\n{page:WordSection1\;}\n--></s
 tyle><!--[if gte mso 9]><xml>\n<o:shapedefaults v:ext="edit" spidmax="1026" 
 />\n</xml><![endif]--><!--[if gte mso 9]><xml>\n<o:shapelayout v:ext="edit">
 \n<o:idmap v:ext="edit" data="1" />\n</o:shapelayout></xml><![endif]--></hea
 d><body lang=EN-US link="#0563C1" vlink="#954F72"><div class=WordSection1><p
  class=MsoNormal><span lang=FR style='font-size:10.0pt\;font-family:"Georgia
 "\,serif'>Voilà une invitation pour la réunion de mercredi.<o:p></o:p></span
 ></p><p class=MsoNormal><span lang=FR style='font-size:10.0pt\;font-family:"
 Georgia"\,serif'>Je propose que l&#8217\;on se retrouve devant le bureau de 
 Ruben (Bureau 2003 de l&#8217\;aile CMAP).<o:p></o:p></span></p><p class=Mso
 Normal><span lang=FR style='font-size:10.0pt\;font-family:"Georgia"\,serif'>
 A plus tard\,<o:p></o:p></span></p><p class=MsoNormal><span lang=FR style='f
 ont-size:10.0pt\;font-family:"Georgia"\,serif'>Nicolas<o:p></o:p></span></p>
 </div></body></html>
LOCATION:Bureau de Ruben 2003 CMAP
ATTENDEE;CN=Ruben Di Battista;PARTSTAT=ACCEPTED:mailto:ruben.di-battista@pol
 ytechnique.edu
ATTENDEE;CN="Assumpção Scripnic Dimitri (M.)":mailto:dimitri.assumpcao-scrip
 nic@polytechnique.edu
PRIORITY:5
ORGANIZER;CN=Nicolas Hanappier:mailto:nicolas.hanappier@polytechnique.edu
DTSTART;TZID="Europe/Brussels":20190918T140000
DTEND;TZID="Europe/Brussels":20190918T150000
STATUS:CONFIRMED
CLASS:PUBLIC
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
TRANSP:OPAQUE
LAST-MODIFIED:20190916T161723Z
DTSTAMP:20190916T161723Z
SEQUENCE:0
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;RELATED=START:-PT5M
DESCRIPTION:Reminder
END:VALARM
END:VEVENT
END:VCALENDAR
``` 

This is the log:
```
[19-09-17 14:15:58:823 CEST] Creating Calendar: Polytechnique
[19-09-17 14:16:14:329 CEST] # of events: 1
[19-09-17 14:16:14:330 CEST] Title: Point C'Space
[19-09-17 14:16:14:331 CEST] Id: 040000008200E00074C5B7101A82E00800000000E012E4FCBA6CD501000000000000000010000000A75FBA59B47C784ABD42E4B8ABC7A329
[19-09-17 14:16:14:331 CEST] Description: Voilà une invitation pour la réunion de mercredi.

Je propose que l’on se retrouve devant le bureau de Ruben (Bureau 2003 de l’aile CMAP).

A plus tard,

Nicolas


[19-09-17 14:16:14:332 CEST] Start: Wed Sep 18 2019 23:00:00 GMT+0200 (CEST)
[19-09-17 14:16:14:332 CEST] End: Thu Sep 19 2019 00:00:00 GMT+0200 (CEST)
[19-09-17 14:16:14:333 CEST] Reminder: 300 seconds before
[19-09-17 14:16:14:333 CEST] 
[19-09-17 14:16:14:466 CEST] Checking 1 Events for creation
[19-09-17 14:16:15:361 CEST]    Created: 040000008200E00074C5B7101A82E00800000000E012E4FCBA6CD501000000000000000010000000A75FBA59B47C784ABD42E4B8ABC7A329
[19-09-17 14:16:15:594 CEST] Checking 0 events for removal or modification
```

The event is created at 23:00 while it should be created at 14:00. 
The timezone of the script is `GMT+1 (Paris)` (Even if it should be GMT+2 Paris)
The timezone of the target calendar is `(GMT+02:00) Central European Time - Paris`

**Comment by jonas0b1011001** [comment]
Please manually replace your code.gs with the [latest version](https://github.com/derekantrican/GAS-ICS-Sync/commit/6302c30ab35499efb86e557a322999e0639ed366) on this repo and try again. The example you posted syncs fine on my end.

**Comment by rubendibattista** [comment]
@jonas0b1011001 That was it. I had an older version. :) It works as expected.
